FROM python:3.13.2

WORKDIR /app

COPY main.py .
COPY server.py .
COPY FinalModel.pt .

RUN pip install ultralytics pathlib

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

EXPOSE 8001

CMD ["python", "server.py"]