FROM python:3.13.2

WORKDIR /app

COPY main.py .
COPY model_server.py .
COPY FinalModel.pt .

RUN pip install ultralytics opencv-python torch torchvision

RUN apt-get update && apt-get install -y ffmpeg libsm6 libxext6 libgl1-mesa-glx libglib2.0-0 && rm -rf /var/lib/apt/lists/*

EXPOSE 8001

CMD ["python", "model_server.py"]